name: Package Application with Pyinstaller

on:
  push:
    branches: 
      - main

jobs:
  build:
    if: contains(github.event.head_commit.message, 'Release')
    runs-on: windows-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Release Tag
        run: echo "RELEASE_TAG=$(echo ${GITHUB_SHA::5})" >> $GITHUB_ENV

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: pip install pyinstaller

      - name: Package Application
        run: pyinstaller --onefile --noconsole --name amsl0_glue_dispenser src/amsl0_glue_dispenser.py

      - name: Create temp application directory
        run: mkdir -p application

      - name: Copy application to temp directory
        run: cp dist/amsl0_glue_dispenser.exe application/

      - name: Copy additional files
        run: |
          cp src/amsl0_glue_dispenser.spec application/
          cp src/icon.ico application/
          cp src/logo.png application/
          cp src/GCode_writer.ipynb application/
          cp README.md application/

      - name: Zip application folder
        run: powershell Compress-Archive -Path application -DestinationPath application.zip
        
      - name: Create Release
        uses: actions/create-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          token: ${{ secrets.MY_PAT }}

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PAT }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./your-file.zip
          asset_name: your-file.zip
          asset_content_type: application/zip