name: Package Application with Pyinstaller

on:
  push:
    branches: 
      - pyinstaller_tests
      - main

jobs:
  build:
    if: contains(github.event.head_commit.message, 'Release')
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Release Tag
        run: echo "RELEASE_TAG=$(echo ${GITHUB_SHA::5})" >> $GITHUB_ENV

      - name: Package Application
        uses: JackMcKew/pyinstaller-action-windows@main
        with:
          path: src

      - name: Create temp application directory
        run: mkdir -p application

      - name: Copy application to temp directory
        run: cp src/dist/windows/amsl0_glue_dispenser.exe application/amsl0_glue_dispenser.exe

      - name: Copy src/voice.mp3 to temp directory
        run: cp src/voice.mp3 application/voice.mp3

      - name: Copy src/logo.png to temp directory
        run: cp src/logo.png application/logo.png

      - name: Copy src/GCode_writer.py to temp directory
        run: cp src/GCode_writer.py application/GCode_writer.py

      - name: Copy README.md to temp directory
        run: cp README.md application/README.md

      - name: Zip application folder
        run: zip -r application.zip application
        
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PAT }}
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          release_name: ${{ env.RELEASE_TAG }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PAT }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: application.zip
          asset_name: application.zip
          asset_content_type: application/octet-stream
